version: "3.4"
services:
  lnd:
    build:
      context: buildLnd
      args:
        UPSTREAM_VERSION: v0.12.0-beta
    image: "lnd.lightning-network.public.dappnode.eth:0.1.0"
    ports:
      - "9735:9735"
    environment:
      ALIAS: null
      MAINNET: null
      COLOR: "#5ACDC5"
    volumes:
      - "lnd_data:/root/.lnd/data"
      - "lnd_shared:/shared"
    restart: always
  rtl:
    build:
      context: buildRtl
      args:
        UPSTREAM_VERSION: 0.10.0
    environment:
      UI_PASSWORD: null
    image: "rtl.lightning-network.public.dappnode.eth:0.1.0"
    volumes:
      - "lnd_shared:/shared"
    restart: always
volumes:
  lnd_data: {}
  lnd_shared: {}
